-- Prints the current schema (tables, constraints, indexes, RLS, policies, views, functions,
-- storage buckets, realtime tables) as one block of SQL. Run it in the Supabase SQL Editor, copy the
-- single result cell, and paste it into supabase/schema.sql. This is NOT a migration: it is a
-- reference snapshot so git shows how the structure changes over time.
-- (Kept outside supabase/migrations/ on purpose so the GitHub integration never runs it.)

with tbl as (
  select c.oid, c.relname, c.relrowsecurity
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind in ('r', 'p')
),
parts as (
  -- 1. tables
  select 1 as k, t.relname as s,
    'create table public.' || quote_ident(t.relname) || E' (\n' ||
    (select string_agg(
        '  ' || quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod) ||
        case a.attidentity when 'a' then ' generated always as identity'
                           when 'd' then ' generated by default as identity' else '' end ||
        coalesce(' default ' || pg_get_expr(d.adbin, d.adrelid), '') ||
        case when a.attnotnull then ' not null' else '' end,
        E',\n' order by a.attnum)
     from pg_attribute a
     left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
     where a.attrelid = t.oid and a.attnum > 0 and not a.attisdropped)
    || E'\n);' as ddl
  from tbl t

  union all
  -- 2. keys and checks, then 3. foreign keys (so referenced tables exist first)
  select case when con.contype = 'f' then 3 else 2 end, t.relname || con.conname,
    'alter table public.' || quote_ident(t.relname) || ' add constraint ' || quote_ident(con.conname) ||
    ' ' || pg_get_constraintdef(con.oid) || ';'
  from pg_constraint con join tbl t on t.oid = con.conrelid
  where con.contype in ('p', 'u', 'c', 'f')

  union all
  -- 4. plain indexes (constraint-backed ones are already covered above)
  select 4, i.indexname, i.indexdef || ';'
  from pg_indexes i
  where i.schemaname = 'public'
    and i.indexname not in (select conname from pg_constraint)

  union all
  -- 5. row level security switches
  select 5, t.relname, 'alter table public.' || quote_ident(t.relname) || ' enable row level security;'
  from tbl t where t.relrowsecurity

  union all
  -- 6. policies (public tables and storage.objects)
  select 6, p.schemaname || p.tablename || p.policyname,
    'create policy ' || quote_ident(p.policyname) || ' on ' || p.schemaname || '.' || quote_ident(p.tablename) ||
    ' as ' || lower(p.permissive) || ' for ' || lower(p.cmd) || ' to ' || array_to_string(p.roles, ', ') ||
    coalesce(' using (' || p.qual || ')', '') ||
    coalesce(' with check (' || p.with_check || ')', '') || ';'
  from pg_policies p
  where p.schemaname in ('public', 'storage') and (p.schemaname = 'public' or p.tablename = 'objects')

  union all
  -- 7. views
  select 7, v.viewname, 'create or replace view public.' || quote_ident(v.viewname) || ' as ' || v.definition
  from pg_views v where v.schemaname = 'public'

  union all
  -- 8. functions
  select 8, p.proname || p.oid::text, pg_get_functiondef(p.oid) || ';'
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.prokind = 'f'

  union all
  -- 9. storage buckets
  select 9, b.id,
    'insert into storage.buckets (id, name, public) values (' || quote_literal(b.id) || ', ' ||
    quote_literal(b.name) || ', ' || b.public || ') on conflict (id) do nothing;'
  from storage.buckets b

  union all
  -- 10. tables published to realtime
  select 10, pt.tablename,
    'alter publication supabase_realtime add table public.' || quote_ident(pt.tablename) || ';'
  from pg_publication_tables pt where pt.pubname = 'supabase_realtime' and pt.schemaname = 'public'
)
select '-- Schema snapshot, generated ' || now()::date || E'\n\n' ||
       string_agg(ddl, E'\n\n' order by k, s) as schema_sql
from parts;
